### ISSUE TITLE
LambdaType should not override finalize()

### ISSUE THREAD

**Issue by A248** [LanternPowered/Lmbda#2]
Despite the intention of overriding this method to make it final, this causes LambdaType objects to be placed in the finalization queue.

https://www.oracle.com/technical-resources/articles/javase/finalization.html

Instead of trying to prevent people from overriding finalize(), let them implement it and cause their own memory leaks. It should be no matter for everyone else.

**Comment by Cybermaxke** [comment]
The problem right now is that the method is non-trivial, making the body empty will make it considered trivial so it will be ignored by the finalizer.

Should be fixed with https://github.com/LanternPowered/Lmbda/commit/b650edb8154edc8136b1f32ca16e0d0e96c4a0b2
