### ISSUE TITLE
Declare optional modular dependencies as static

### ISSUE THREAD

**Issue by A248** [LanternPowered/Lmbda#3]
The build.gradle notes the dependencies on Guava and the Kotlin standard library are optional.

However, the module descriptor does not use the `static` modifier, which makes them mandatory:
```java
open module org.lanternpowered.lmbda {
    requires org.objectweb.asm;
    requires kotlin.stdlib;
    requires com.google.common;

    exports org.lanternpowered.lmbda;
    exports org.lanternpowered.lmbda.kt;
}
```

As a somewhat related question, why is the module made `open`? Does one of Lmbda's dependencies reflect into the main code? I do not think ASM, Guava, or Kotlin would do that.

**Comment by Cybermaxke** [comment]
It looks like the compiled module descriptor is not up-to-date, the actual module source file marks the kotlin and google library as optional. As for why the module is open, I can't remember why I made it open so I guess that can be removed.

**Comment by Cybermaxke** [comment]
I updated the module-info in the 3.x branch, so it's no longer an open module. The static modifier is a bit strange though, the source file contains static but when decompiling it's no longer there, but I assume it won't be a problem.
