### ISSUE TITLE
Couldn't create lambda

### ISSUE THREAD

**Issue by Katzen48** [LanternPowered/Lmbda#4]
I got sent here from the [Velocity](https://github.com/PaperMC/Velocity) Discord because of an exception, I am getting from your library.

Velocity uses your library internally and I get the following StackTrace: [https://pastebin.com/pvhMVwQT](https://pastebin.com/pvhMVwQT), when Velocity loads my plugin: [https://github.com/Katzen48/minecraft-ingress](https://github.com/Katzen48/minecraft-ingress)

**Comment by Cybermaxke** [comment]
Hi @Katzen48, for now put your plugin classes in a package, this is a better practice anyway. But I will further look into the issue.

**Comment by Katzen48** [comment]
Thanks, inside a package, the plugin loaded correctly.
Still, that's a strange behaviour.

**Comment by Cybermaxke** [comment]
This issue has been resolved in the 3.x branch and is now covered by unit tests.
